#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 14 19:52:22 EDT 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim uart_tx_tb_behav -key {Behavioral:sim_1:Functional:uart_tx_tb} -tclbatch uart_tx_tb.tcl -view /home/shay/a/rabdubae/Type-1-Compute/project_1/flex_counter_tb_behav.wcfg -log simulate.log"
xsim uart_tx_tb_behav -key {Behavioral:sim_1:Functional:uart_tx_tb} -tclbatch uart_tx_tb.tcl -view /home/shay/a/rabdubae/Type-1-Compute/project_1/flex_counter_tb_behav.wcfg -log simulate.log

